#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "retina_lexer"
require_relative "retina_ast"

class SyntacticError < RuntimeError

    def initialize(tok)
        @token = tok
    end

    def to_s
        "Syntactic error on line #{@token.line}, column #{@token.column}: #{@token.value}"   
    end
end

class Parser < Racc::Parser

module_eval(<<'...end retina_parser.y/module_eval...', 'retina_parser.y', 224)

def on_error(id, token, stack)
    raise SyntacticError::new(token)
end

def next_token
    if @lexer.has_next_token then
        token = @lexer.next_token;
        return [token.symbol,token]
    else
        return [false,false];
    end
end

def parse(lexer)
    @yydebug = true
    @lexer = lexer
    @tokens = []
    ast = do_parse
    return ast
end
...end retina_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    32,    60,    82,    32,   157,    80,    35,    71,    72,    35,
    69,    60,    32,     4,   158,   135,    90,    13,    35,    19,
    32,    16,    14,    15,    20,     5,    35,    17,    18,    32,
    73,    74,    32,    59,   136,    35,    37,    31,    35,    37,
    31,    38,    70,    10,    38,    48,    10,    35,    37,    31,
    35,     7,    32,    38,    48,    10,    37,    31,    35,   118,
   -59,    38,    73,    10,     4,    37,    31,    10,    37,    31,
    38,    11,    10,    38,    32,    10,   214,    32,    56,    39,
    35,    56,    38,    35,    10,    38,   215,    10,    37,    31,
    73,    74,    40,    38,    13,    10,    19,    35,    16,    14,
    15,    20,    32,    43,    17,    18,   -76,   -76,    35,   -76,
    37,    31,    10,    37,    31,    38,    10,    10,    38,    13,
    10,    19,    35,    16,    14,    15,    20,    32,    56,    17,
    18,    61,    38,    35,    10,    37,    62,   105,    37,    31,
    38,   -76,    10,    38,    13,    10,    19,    35,    16,    14,
    15,    20,    32,    56,    17,    18,    63,    38,    35,    10,
    68,   126,    64,    37,    31,    73,    74,    65,    38,    13,
    10,    19,    35,    16,    14,    15,    20,    32,    56,    17,
    18,    95,    38,    35,    10,    66,    83,    43,    37,    31,
    73,    74,    85,    38,    13,    10,    19,    35,    16,    14,
    15,    20,    32,    56,    17,    18,   186,    38,    35,    10,
    37,    10,    89,    37,    31,    38,    32,    10,    38,    13,
    10,    19,    35,    16,    14,    15,    20,    32,    56,    17,
    18,    60,    38,    35,    10,    32,    92,    67,    37,    31,
   -59,    35,    70,    38,    13,    10,    19,   119,    16,    14,
    15,    20,    37,    31,    17,    18,    32,    38,   120,    10,
    71,    72,    35,    37,    31,    35,   121,    32,    38,    10,
    10,    37,    31,    35,   123,    32,    38,   124,    10,    71,
    72,    35,    73,    74,    32,   125,   -85,    71,    72,   133,
    35,    91,    37,    31,    93,    70,    56,    38,   134,    10,
    38,    60,    10,    37,    31,    35,    70,    32,    38,    48,
    10,    37,    31,    35,    70,    70,    38,    48,    10,   -59,
    37,    31,    70,    82,    13,    38,    19,    10,    16,    14,
    15,    20,    32,    10,    17,    18,    56,   154,    35,   156,
    38,   161,    10,    37,    31,   162,   163,    43,    38,    13,
    10,    19,    35,    16,    14,    15,    20,    32,    10,    17,
    18,    71,    72,    35,   170,   171,   172,   173,    37,    31,
   175,   126,   178,    38,    13,    10,    19,    35,    16,    14,
    15,    20,    32,    56,    17,    18,   155,    38,    35,    10,
   179,   180,   182,    37,    31,   184,    70,    60,    38,   139,
    10,   142,    35,    16,    14,    15,   143,    32,    56,   140,
   141,   193,    38,    35,    10,   149,   138,   194,    37,    31,
   196,    32,   197,    38,    13,    10,    19,    35,    16,    14,
    15,    20,    32,    56,    17,    18,   207,    38,    35,    10,
   208,   211,   213,    37,    31,   217,    71,    72,    38,   139,
    10,   142,   218,    16,    14,    15,   143,    37,    31,   140,
   141,    32,    38,   219,    10,   149,   225,    35,    37,    31,
    32,   226,   231,    38,   234,    10,    35,   nil,   139,   117,
   142,    70,    16,    14,    15,   143,    73,    74,   140,   141,
   nil,    35,   nil,    32,   149,   183,    35,    37,    31,    35,
   nil,   nil,    38,   nil,    10,   nil,    37,    31,   nil,   nil,
    13,    38,    19,    10,    16,    14,    15,    20,    32,   nil,
    17,    18,    56,   nil,    35,   nil,    38,    56,    10,    37,
    31,    38,   nil,    10,    38,   139,    10,   142,   nil,    16,
    14,    15,   143,    32,   nil,   140,   141,    71,    72,    35,
   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,    38,
   139,    10,   142,   nil,    16,    14,    15,   143,    32,   nil,
   140,   141,   212,   nil,    35,   nil,   149,   nil,   nil,    37,
    31,   nil,    70,   nil,    38,   139,    10,   142,   nil,    16,
    14,    15,   143,    32,   nil,   140,   141,   nil,   nil,    35,
   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,    38,
   139,    10,   142,   nil,    16,    14,    15,   143,    32,   nil,
   140,   141,   nil,   nil,    35,   nil,   149,   nil,   nil,    37,
    31,   nil,   nil,   nil,    38,   139,    10,   142,   nil,    16,
    14,    15,   143,    32,   nil,   140,   141,   nil,   nil,    35,
   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,    38,
   139,    10,   142,   nil,    16,    14,    15,   143,    32,   nil,
   140,   141,   nil,   nil,    35,   nil,   149,   nil,   nil,    37,
    31,   nil,   nil,   nil,    38,   139,    10,   142,   nil,    16,
    14,    15,   143,    32,   nil,   140,   141,   nil,   nil,    35,
   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,    38,
   139,    10,   142,   nil,    16,    14,    15,   143,    32,   nil,
   140,   141,   nil,   nil,    35,   nil,   149,   nil,   nil,    37,
    31,   nil,   nil,   nil,    38,   139,    10,   142,   nil,    16,
    14,    15,   143,    32,   nil,   140,   141,   nil,   nil,    35,
   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,    38,
    13,    10,    19,   nil,    16,    14,    15,    20,    32,   nil,
    17,    18,   nil,   nil,    35,   -75,   -75,   nil,   -75,    37,
    31,    68,   nil,   nil,    38,   139,    10,   142,   nil,    16,
    14,    15,   143,    71,    72,   140,   141,    32,   nil,   nil,
   nil,   149,   nil,    35,    37,    31,   nil,    67,   185,    38,
   -75,    10,   nil,   154,   139,   nil,   142,   nil,    16,    14,
    15,   143,    71,    72,   140,   141,    32,   nil,    70,   nil,
   149,   nil,    35,    37,    31,   216,   nil,   nil,    38,   nil,
    10,   nil,   156,   139,   nil,   142,   nil,    16,    14,    15,
   143,    71,    72,   140,   141,    32,   nil,    70,   nil,   149,
   nil,    35,    37,    31,   230,   nil,   nil,    38,   nil,    10,
   nil,   157,   139,   nil,   142,   nil,    16,    14,    15,   143,
   nil,   158,   140,   141,    32,   nil,    70,   nil,   149,   nil,
    35,    37,    31,   nil,   nil,   nil,    38,   nil,    10,   nil,
   175,   139,   nil,   142,   nil,    16,    14,    15,   143,    32,
   nil,   140,   141,   nil,   nil,    35,   nil,   149,   nil,   nil,
    37,    31,   nil,   nil,   nil,    38,   139,    10,   142,   nil,
    16,    14,    15,   143,    32,   nil,   140,   141,   nil,   nil,
    35,   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,
    38,    13,    10,    19,   nil,    16,    14,    15,    20,    32,
   nil,    17,    18,   nil,   nil,    35,   -75,   -75,   nil,   -75,
    37,    31,   nil,   nil,   nil,    38,   139,    10,   142,   nil,
    16,    14,    15,   143,   nil,   nil,   140,   141,    32,   nil,
   nil,   nil,   149,   nil,    35,    37,    31,   nil,    67,   nil,
    38,   -75,    10,   nil,   217,   139,   nil,   142,   nil,    16,
    14,    15,   143,    32,   nil,   140,   141,   nil,   nil,    35,
   nil,   149,   nil,   nil,    37,    31,   nil,   nil,   nil,    38,
   139,    10,   142,   nil,    16,    14,    15,   143,   nil,   nil,
   140,   141,    32,   nil,   nil,   nil,   149,   nil,    35,    37,
    31,   nil,   nil,   nil,    38,   nil,    10,   nil,   226,   139,
   nil,   142,   nil,    16,    14,    15,   143,    71,    72,   140,
   141,    71,    72,   nil,    69,   149,   nil,   nil,    37,    31,
   192,    71,    72,    38,   nil,    10,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   191,   224,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    70,   nil,   117,   nil,    70,   223,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    70 ]

racc_action_check = [
     7,    21,    39,    14,   132,    39,     7,    29,    29,    14,
    29,    47,    15,     0,   132,   119,    47,     7,    15,     7,
    17,     7,     7,     7,     7,     1,    17,     7,     7,    20,
    76,    76,    31,    21,   119,    20,     7,     7,    31,    14,
    14,     7,    29,     7,    14,    14,    14,    19,    15,    15,
    35,     2,    32,    15,    15,    15,    17,    17,    32,    76,
   116,    17,   116,    17,     3,    20,    20,     4,    31,    31,
    20,     5,    20,    31,    60,    31,   204,    59,    19,     9,
    60,    35,    19,    59,    19,    35,   204,    35,    32,    32,
    30,    30,    12,    32,    59,    32,    59,    56,    59,    59,
    59,    59,    61,    13,    59,    59,    34,    34,    61,    34,
    60,    60,    16,    59,    59,    60,    18,    60,    59,    61,
    59,    61,    69,    61,    61,    61,    61,    62,    56,    61,
    61,    22,    56,    62,    56,    67,    23,    67,    61,    61,
    67,    34,    67,    61,    62,    61,    62,    70,    62,    62,
    62,    62,    63,    69,    62,    62,    24,    69,    63,    69,
    88,    88,    25,    62,    62,    58,    58,    26,    62,    63,
    62,    63,    71,    63,    63,    63,    63,    64,    70,    63,
    63,    58,    70,    64,    70,    27,    40,    41,    63,    63,
   168,   168,    42,    63,    64,    63,    64,    72,    64,    64,
    64,    64,    65,    71,    64,    64,   168,    71,    65,    71,
   134,    43,    46,    64,    64,   134,    68,   134,    64,    65,
    64,    65,    68,    65,    65,    65,    65,    66,    72,    65,
    65,    52,    72,    66,    72,    73,    53,    55,    65,    65,
    77,    73,    78,    65,    66,    65,    66,    79,    66,    66,
    66,    66,    68,    68,    66,    66,    74,    68,    80,    68,
   111,   111,    74,    66,    66,    92,    81,    89,    66,    82,
    66,    73,    73,    89,    85,    90,    73,    86,    73,    54,
    54,    90,    51,    51,   140,    87,    97,   112,   112,   104,
   140,    51,    74,    74,    54,   111,    92,    74,   106,    74,
    92,   110,    92,    89,    89,   142,   113,    91,    89,    89,
    89,    90,    90,    91,    54,   114,    90,    90,    90,   115,
   140,   140,   112,   121,    91,   140,    91,   140,    91,    91,
    91,    91,    93,   126,    91,    91,   142,   129,    93,   131,
   142,   136,   142,    91,    91,   137,   138,   139,    91,    93,
    91,    93,   155,    93,    93,    93,    93,    95,   141,    93,
    93,   130,   130,    95,   145,   146,   147,   148,    93,    93,
   151,   152,   160,    93,    95,    93,    95,   184,    95,    95,
    95,    95,   120,   155,    95,    95,   130,   155,   120,   155,
   161,   162,   164,    95,    95,   166,   130,   174,    95,   120,
    95,   120,   191,   120,   120,   120,   120,   123,   184,   120,
   120,   177,   184,   123,   184,   120,   120,   178,   120,   120,
   181,   143,   182,   120,   123,   120,   123,   143,   123,   123,
   123,   123,   135,   191,   123,   123,   195,   191,   135,   191,
   196,   199,   202,   123,   123,   206,    94,    94,   123,   135,
   123,   135,   207,   135,   135,   135,   135,   143,   143,   135,
   135,   144,   143,   210,   143,   135,   221,   144,   135,   135,
   149,   222,   229,   135,   233,   135,   149,   nil,   144,    94,
   144,    94,   144,   144,   144,   144,   165,   165,   144,   144,
   nil,   212,   nil,   158,   144,   165,   223,   144,   144,   158,
   nil,   nil,   144,   nil,   144,   nil,   149,   149,   nil,   nil,
   158,   149,   158,   149,   158,   158,   158,   158,   163,   nil,
   158,   158,   212,   nil,   163,   nil,   212,   223,   212,   158,
   158,   223,   nil,   223,   158,   163,   158,   163,   nil,   163,
   163,   163,   163,   170,   nil,   163,   163,   200,   200,   170,
   nil,   163,   nil,   nil,   163,   163,   nil,   nil,   nil,   163,
   170,   163,   170,   nil,   170,   170,   170,   170,   171,   nil,
   170,   170,   200,   nil,   171,   nil,   170,   nil,   nil,   170,
   170,   nil,   200,   nil,   170,   171,   170,   171,   nil,   171,
   171,   171,   171,   172,   nil,   171,   171,   nil,   nil,   172,
   nil,   171,   nil,   nil,   171,   171,   nil,   nil,   nil,   171,
   172,   171,   172,   nil,   172,   172,   172,   172,   173,   nil,
   172,   172,   nil,   nil,   173,   nil,   172,   nil,   nil,   172,
   172,   nil,   nil,   nil,   172,   173,   172,   173,   nil,   173,
   173,   173,   173,   179,   nil,   173,   173,   nil,   nil,   179,
   nil,   173,   nil,   nil,   173,   173,   nil,   nil,   nil,   173,
   179,   173,   179,   nil,   179,   179,   179,   179,   183,   nil,
   179,   179,   nil,   nil,   183,   nil,   179,   nil,   nil,   179,
   179,   nil,   nil,   nil,   179,   183,   179,   183,   nil,   183,
   183,   183,   183,   185,   nil,   183,   183,   nil,   nil,   185,
   nil,   183,   nil,   nil,   183,   183,   nil,   nil,   nil,   183,
   185,   183,   185,   nil,   185,   185,   185,   185,   186,   nil,
   185,   185,   nil,   nil,   186,   nil,   185,   nil,   nil,   185,
   185,   nil,   nil,   nil,   185,   186,   185,   186,   nil,   186,
   186,   186,   186,   192,   nil,   186,   186,   nil,   nil,   192,
   nil,   186,   nil,   nil,   186,   186,   nil,   nil,   nil,   186,
   192,   186,   192,   nil,   192,   192,   192,   192,   197,   nil,
   192,   192,   nil,   nil,   197,    28,    28,   nil,    28,   192,
   192,    28,   nil,   nil,   192,   197,   192,   197,   nil,   197,
   197,   197,   197,   167,   167,   197,   197,   198,   nil,   nil,
   nil,   197,   nil,   198,   197,   197,   nil,    28,   167,   197,
    28,   197,   nil,   198,   198,   nil,   198,   nil,   198,   198,
   198,   198,   205,   205,   198,   198,   201,   nil,   167,   nil,
   198,   nil,   201,   198,   198,   205,   nil,   nil,   198,   nil,
   198,   nil,   201,   201,   nil,   201,   nil,   201,   201,   201,
   201,   227,   227,   201,   201,   203,   nil,   205,   nil,   201,
   nil,   203,   201,   201,   227,   nil,   nil,   201,   nil,   201,
   nil,   203,   203,   nil,   203,   nil,   203,   203,   203,   203,
   nil,   203,   203,   203,   209,   nil,   227,   nil,   203,   nil,
   209,   203,   203,   nil,   nil,   nil,   203,   nil,   203,   nil,
   209,   209,   nil,   209,   nil,   209,   209,   209,   209,   215,
   nil,   209,   209,   nil,   nil,   215,   nil,   209,   nil,   nil,
   209,   209,   nil,   nil,   nil,   209,   215,   209,   215,   nil,
   215,   215,   215,   215,   216,   nil,   215,   215,   nil,   nil,
   216,   nil,   215,   nil,   nil,   215,   215,   nil,   nil,   nil,
   215,   216,   215,   216,   nil,   216,   216,   216,   216,   224,
   nil,   216,   216,   nil,   nil,   224,    45,    45,   nil,    45,
   216,   216,   nil,   nil,   nil,   216,   224,   216,   224,   nil,
   224,   224,   224,   224,   nil,   nil,   224,   224,   228,   nil,
   nil,   nil,   224,   nil,   228,   224,   224,   nil,    45,   nil,
   224,    45,   224,   nil,   228,   228,   nil,   228,   nil,   228,
   228,   228,   228,   230,   nil,   228,   228,   nil,   nil,   230,
   nil,   228,   nil,   nil,   228,   228,   nil,   nil,   nil,   228,
   230,   228,   230,   nil,   230,   230,   230,   230,   nil,   nil,
   230,   230,   232,   nil,   nil,   nil,   230,   nil,   232,   230,
   230,   nil,   nil,   nil,   230,   nil,   230,   nil,   232,   232,
   nil,   232,   nil,   232,   232,   232,   232,   176,   176,   232,
   232,    75,    75,   nil,    75,   232,   nil,   nil,   232,   232,
   176,   220,   220,   232,   nil,   232,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   176,   220,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   176,   nil,    75,   nil,    75,   220,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   220 ]

racc_action_pointer = [
   -23,    25,    33,    28,    20,    71,   nil,    -4,   nil,    38,
   nil,   nil,    72,    64,    -1,     8,    65,    16,    69,    37,
    25,   -10,    88,    93,   113,   119,   124,   142,   766,    -2,
    77,    28,    48,   nil,    97,    40,   nil,   nil,   nil,   -37,
   143,   148,   149,   164,   nil,   957,   196,     0,   nil,   nil,
   nil,   269,   220,   203,   270,   196,    87,   nil,   152,    73,
    70,    98,   123,   148,   173,   198,   223,    95,   212,   112,
   137,   162,   187,   231,   252,  1062,    17,   229,   198,   205,
   239,   250,   222,   nil,   nil,   252,   234,   242,   145,   263,
   271,   303,   255,   328,   437,   353,   nil,   275,   nil,   nil,
   nil,   nil,   nil,   nil,   247,   nil,   282,   nil,   nil,   nil,
   290,   251,   278,   262,   271,   308,    49,   nil,   nil,    -4,
   378,   284,   nil,   403,   nil,   nil,   286,   nil,   nil,   317,
   352,   319,   -16,   nil,   170,   428,   302,   325,   307,   308,
   280,   311,   295,   417,   457,   321,   322,   323,   324,   466,
   nil,   350,   355,   nil,   nil,   342,   nil,   nil,   489,   nil,
   352,   371,   348,   514,   349,   473,   362,   784,   177,   nil,
   539,   564,   589,   614,   386,   nil,  1058,   391,   374,   639,
   nil,   400,   400,   664,   367,   689,   714,   nil,   nil,   nil,
   nil,   392,   739,   nil,   nil,   416,   397,   764,   793,   421,
   538,   822,   422,   851,    56,   813,   425,   409,   nil,   880,
   443,   nil,   481,   nil,   nil,   905,   930,   nil,   nil,   nil,
  1072,   446,   451,   486,   955,   nil,   nil,   842,   984,   452,
  1009,   nil,  1038,   454,   nil ]

racc_action_default = [
    -5,   -85,    -2,    -5,   -85,   -85,    -1,   -42,    -4,   -85,
   -84,   235,   -85,   -11,   -85,   -85,   -85,   -85,   -85,   -85,
   -85,   -85,   -85,   -85,   -85,   -85,   -85,   -85,   -67,   -58,
   -59,   -85,   -85,   -66,   -68,   -85,   -74,   -82,   -83,   -85,
   -85,   -11,   -85,   -85,   -14,   -67,   -85,   -85,   -81,   -15,
   -16,   -59,   -85,   -85,   -85,   -75,   -85,   -76,   -59,   -42,
   -85,   -42,   -42,   -42,   -42,   -42,   -42,   -85,   -85,   -85,
   -85,   -85,   -85,   -85,   -85,   -58,   -59,   -63,   -73,   -85,
   -85,   -50,   -85,    -3,   -10,   -85,   -85,   -85,   -54,   -85,
   -85,   -42,   -85,   -42,   -85,   -42,   -35,   -64,   -36,   -37,
   -38,   -39,   -40,   -41,   -85,   -44,   -52,   -78,   -79,   -80,
   -55,   -65,   -69,   -70,   -71,   -60,   -61,   -72,   -62,   -85,
   -34,   -85,   -77,   -42,   -45,   -46,   -85,   -47,   -48,   -85,
   -85,   -85,   -85,   -43,   -85,   -34,   -85,   -85,   -85,   -11,
   -85,   -85,   -85,   -85,   -34,   -85,   -85,   -85,   -85,   -56,
   -49,   -85,   -54,   -53,   -17,   -85,   -20,   -25,   -42,   -51,
   -85,   -85,   -85,   -34,   -85,   -59,   -85,   -85,   -59,   -29,
   -34,   -34,   -34,   -34,   -57,   -12,   -85,   -85,   -85,   -34,
    -8,   -85,   -85,   -34,   -85,   -34,   -34,   -30,   -31,   -32,
   -33,   -85,   -42,   -26,    -6,   -85,   -85,   -34,   -85,   -85,
   -85,   -85,   -85,   -85,   -85,   -85,   -85,   -85,    -9,   -85,
   -85,   -21,   -85,   -24,   -27,   -34,   -42,   -19,    -7,   -13,
   -85,   -85,   -85,   -85,   -34,   -28,   -18,   -85,   -85,   -85,
   -34,   -23,   -85,   -85,   -22 ]

racc_goto_table = [
    12,    42,    86,   104,     2,   107,   108,     8,    79,     1,
     6,     9,    87,   nil,   nil,   nil,    44,    49,   nil,   nil,
   nil,    45,    45,    50,    45,    53,    55,    45,   nil,    84,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    45,    45,
   nil,   nil,    55,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    88,   nil,    96,   nil,    98,    99,   100,   101,   102,   103,
   nil,   nil,   nil,    55,   nil,   nil,   nil,    45,   nil,   nil,
   159,    54,   107,   108,   109,    45,    55,    55,    55,    55,
    45,    45,   nil,    75,   129,   153,   131,    78,   132,   122,
   150,   127,   128,   nil,   nil,   nil,    45,    45,   nil,    55,
   nil,   nil,    57,   nil,   nil,   nil,   nil,   nil,    94,   nil,
   nil,    47,    47,   nil,    52,   nil,   151,    52,    57,   nil,
   nil,   111,   112,   113,   114,   nil,   nil,   164,    52,    52,
   nil,   nil,   nil,   152,   nil,   nil,   nil,   nil,   nil,    57,
   nil,   109,   nil,   nil,   130,   nil,   nil,    45,   166,    55,
    45,   177,    57,    57,    57,    57,    45,    97,    51,   nil,
   nil,    58,    55,   nil,   nil,   110,   nil,   nil,   nil,   nil,
    52,    52,    76,    77,   nil,    57,   198,   nil,   201,   203,
   nil,   nil,   nil,   nil,   nil,   206,    47,    47,   nil,   nil,
   209,    55,   nil,   nil,   167,   nil,   nil,   nil,    55,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   137,   176,   nil,   222,
   nil,   nil,   nil,   nil,   115,   116,   nil,   228,   nil,    55,
   nil,   160,   nil,   232,   nil,    57,   nil,   nil,   nil,   nil,
    55,   nil,   nil,   nil,   nil,   nil,   200,    52,    57,   nil,
    52,   nil,   nil,   205,   nil,   nil,   174,   nil,   nil,   181,
   nil,   nil,   nil,   nil,   nil,   nil,   187,   188,   189,   190,
   nil,   nil,   nil,   nil,   220,   195,   nil,    57,   nil,   199,
   nil,   202,   204,   nil,    57,   227,   nil,   nil,   nil,   nil,
   nil,   165,   nil,   210,   168,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    57,   nil,   nil,   nil,   nil,
   nil,   221,   nil,   nil,   nil,   nil,    57,   nil,   nil,   nil,
   229,   nil,   nil,   nil,   nil,   nil,   233 ]

racc_goto_check = [
     4,     9,    27,    26,     2,    31,    32,     2,     7,     1,
     3,     6,    24,   nil,   nil,   nil,    14,    14,   nil,   nil,
   nil,     6,     6,     6,     6,     6,     6,     6,   nil,     9,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,     6,
   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     6,   nil,     4,   nil,     4,     4,     4,     4,     4,     4,
   nil,   nil,   nil,     6,   nil,   nil,   nil,     6,   nil,   nil,
    26,    18,    31,    32,     6,     6,     6,     6,     6,     6,
     6,     6,   nil,    18,     4,    27,     4,    18,     4,     6,
     7,    14,    14,   nil,   nil,   nil,     6,     6,   nil,     6,
   nil,   nil,    25,   nil,   nil,   nil,   nil,   nil,    18,   nil,
   nil,    23,    23,   nil,    23,   nil,     4,    23,    25,   nil,
   nil,    18,    18,    18,    18,   nil,   nil,     9,    23,    23,
   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,    25,
   nil,     6,   nil,   nil,    18,   nil,   nil,     6,     6,     6,
     6,     4,    25,    25,    25,    25,     6,    23,    17,   nil,
   nil,    17,     6,   nil,   nil,    23,   nil,   nil,   nil,   nil,
    23,    23,    17,    17,   nil,    25,     4,   nil,     4,     4,
   nil,   nil,   nil,   nil,   nil,     4,    23,    23,   nil,   nil,
     4,     6,   nil,   nil,    18,   nil,   nil,   nil,     6,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     8,    18,   nil,     4,
   nil,   nil,   nil,   nil,    17,    17,   nil,     4,   nil,     6,
   nil,     8,   nil,     4,   nil,    25,   nil,   nil,   nil,   nil,
     6,   nil,   nil,   nil,   nil,   nil,    18,    23,    25,   nil,
    23,   nil,   nil,    18,   nil,   nil,    23,   nil,   nil,     8,
   nil,   nil,   nil,   nil,   nil,   nil,     8,     8,     8,     8,
   nil,   nil,   nil,   nil,    18,     8,   nil,    25,   nil,     8,
   nil,     8,     8,   nil,    25,    18,   nil,   nil,   nil,   nil,
   nil,    17,   nil,     8,    17,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,
   nil,     8,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,     9,     4,     8,    -7,   nil,     7,   -31,    86,   -12,
   nil,   nil,   nil,   nil,     2,   nil,   nil,   141,    52,   nil,
   nil,   nil,   nil,    97,   -31,    83,   -64,   -41,   nil,   nil,
   nil,   -62,   -61 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   144,     3,    28,   nil,   169,   nil,
    41,    27,   147,    26,   nil,    25,    24,    30,    29,   146,
    23,   145,   148,    21,    22,    34,   nil,   nil,    46,    81,
   106,    33,    36 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 49, :_reduce_none,
  1, 49, :_reduce_none,
  4, 51, :_reduce_none,
  2, 50, :_reduce_none,
  0, 50, :_reduce_none,
  9, 53, :_reduce_none,
  11, 53, :_reduce_none,
  8, 53, :_reduce_none,
  10, 53, :_reduce_none,
  2, 57, :_reduce_none,
  0, 57, :_reduce_none,
  6, 59, :_reduce_none,
  6, 60, :_reduce_none,
  2, 61, :_reduce_none,
  2, 61, :_reduce_none,
  2, 63, :_reduce_none,
  5, 64, :_reduce_none,
  11, 64, :_reduce_none,
  9, 64, :_reduce_none,
  5, 64, :_reduce_none,
  5, 67, :_reduce_none,
  11, 67, :_reduce_none,
  9, 67, :_reduce_none,
  5, 67, :_reduce_none,
  5, 68, :_reduce_none,
  7, 68, :_reduce_none,
  5, 69, :_reduce_none,
  7, 69, :_reduce_none,
  2, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  0, 56, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  0, 52, :_reduce_none,
  4, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 58, :_reduce_none,
  3, 58, :_reduce_none,
  3, 62, :_reduce_none,
  3, 62, :_reduce_none,
  3, 55, :_reduce_none,
  1, 55, :_reduce_none,
  3, 74, :_reduce_none,
  1, 74, :_reduce_none,
  3, 75, :_reduce_none,
  1, 75, :_reduce_none,
  3, 72, :_reduce_none,
  1, 70, :_reduce_none,
  2, 70, :_reduce_none,
  1, 71, :_reduce_none,
  1, 71, :_reduce_none,
  3, 65, :_reduce_none,
  3, 65, :_reduce_none,
  3, 65, :_reduce_none,
  2, 65, :_reduce_none,
  3, 65, :_reduce_none,
  3, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  3, 66, :_reduce_none,
  3, 66, :_reduce_none,
  3, 66, :_reduce_none,
  3, 66, :_reduce_none,
  2, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  1, 66, :_reduce_none,
  2, 77, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 76, :_reduce_none,
  1, 79, :_reduce_none,
  1, 80, :_reduce_none,
  1, 54, :_reduce_none ]

racc_reduce_n = 85

racc_shift_n = 235

racc_token_table = {
  false => 0,
  :error => 1,
  :APRNTS => 2,
  :BPRNTS => 3,
  :NOT => 4,
  :UMINUS => 5,
  :MULT => 6,
  :DIV => 7,
  :MOD => 8,
  :PLUS => 9,
  :MINUS => 10,
  :EQUALITYOP => 11,
  :ORDEROP => 12,
  :AND => 13,
  :OR => 14,
  :ASSIGNOP => 15,
  :COLON => 16,
  :SEMICOLON => 17,
  :PROGRAM => 18,
  :BEGINBLK => 19,
  :ENDBLK => 20,
  :WITH => 21,
  :DO => 22,
  :REPEAT => 23,
  :TIMES => 24,
  :READ => 25,
  :WRITE => 26,
  :WRITELN => 27,
  :IF => 28,
  :THEN => 29,
  :ELSE => 30,
  :WHILE => 31,
  :FOR => 32,
  :FROM => 33,
  :TO => 34,
  :BY => 35,
  :FUNC => 36,
  :RETURN => 37,
  :RETURNTYPE => 38,
  :TYPE => 39,
  :BOOLEAN => 40,
  :LPARENTH => 41,
  :RPARENTH => 42,
  :SEP => 43,
  :ARITHMETICOP => 44,
  :NUMBER => 45,
  :STRING => 46,
  :IDENTIFIER => 47 }

racc_nt_base = 48

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "APRNTS",
  "BPRNTS",
  "NOT",
  "UMINUS",
  "MULT",
  "DIV",
  "MOD",
  "PLUS",
  "MINUS",
  "EQUALITYOP",
  "ORDEROP",
  "AND",
  "OR",
  "ASSIGNOP",
  "COLON",
  "SEMICOLON",
  "PROGRAM",
  "BEGINBLK",
  "ENDBLK",
  "WITH",
  "DO",
  "REPEAT",
  "TIMES",
  "READ",
  "WRITE",
  "WRITELN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "FROM",
  "TO",
  "BY",
  "FUNC",
  "RETURN",
  "RETURNTYPE",
  "TYPE",
  "BOOLEAN",
  "LPARENTH",
  "RPARENTH",
  "SEP",
  "ARITHMETICOP",
  "NUMBER",
  "STRING",
  "IDENTIFIER",
  "$start",
  "retina",
  "defblk",
  "programblk",
  "instr",
  "funcdef",
  "ident",
  "paramlist",
  "funcinstr",
  "declblk",
  "decl",
  "withblk",
  "funcwithblk",
  "writeblk",
  "writelist",
  "readblk",
  "iter",
  "bexpr",
  "aexpr",
  "funciter",
  "cond",
  "funccond",
  "returnblk",
  "expr",
  "assign",
  "callfunc",
  "termlist",
  "identlist",
  "str",
  "param",
  "terminal",
  "b",
  "n" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
