#
# 	Traductores e Interpretadores CI-3725
# 	
# 	Proyecto Fase 4 - Interpreter
#
#  	Retina Drawing Library
#
# 	Autores:
# 				- Jose Acevedo		13-10006
#               - Edwar Yepez       12-10855
#

# Image generated by Retina program
class Image

	def initialize(height=11, width=11, cursor_x=0, cursor_y=0, degree=90, opened_eye=true)
		@height = height.to_i
		@width = width.to_i
		@image = Array.new(@height) { Array.new(@width) { 0 } }
		@cursor_column = convert_x_to_column(cursor_x)
		@cursor_row = convert_y_to_row(cursor_y)
		@degree = degree
		@opened_eye = opened_eye

		# Mark initial position
		@image[@cursor_row][@cursor_column] = 1
	end

	# Check if function is predefined
	def is_retina_function(funcIdent)
		# Return true if match found
		return ["home","openeye","closeeye","forward","backward","rotater","rotatel","setposition","arc"].include? funcIdent
	end

	def call_retina_function(funcIdent, arg1 = nil, arg2 = nil)
		# If match found then call function
		case funcIdent
		when "home"
			home()
		
		when "openeye"
			openeye()
		
		when "closeeye"
			closeeye()
		
		when "forward"
			steps = arg1
			forward(steps)
		
		when "backward"
			steps = arg1
			backward(steps)
		
		when "rotater"
			degree = arg1
			rotater(degree)
		
		when "rotatel"
			degree = arg1
			rotatel(degree)
		
		when "setposition"
			x = arg1
			y = arg2
			setposition(x,y)
		
		when "arc"
			degree = arg1
			radius = funcCall.arglist.arglist.arg.value.value.to_f
			arc(degree,radius)
		
		end
	end

	# Reset cursor coordinates to center of image	
	def home()
		@cursor_row = ((@height-1)/2).to_i
		@cursor_column = ((@width-1)/2).to_i
	end
	
	# Enable cursor to mark movement
	def openeye()
		@opened_eye = true
	end
	
	# Disable cursor to mark movement
	def closeeye()
		@opened_eye = false
	end
	
	def forward(steps)
	end
	
	def backward(steps)
	end
	
	# Rotate cursor clockwise
	def rotater(rotationDegree)
		@degree = (@degree - rotationDegree) % 360;
	end
	
	# Rotate cursor counterclockwise
	def rotatel(rotationDegree)
		@degree = (@degree + rotationDegree) % 360;
	end
	
	# Set cursor coordinates
	def setposition(x,y)
		@cursor_column = convert_x_to_column(x)
		@cursor_row = convert_y_to_row(y)
	end
	
	def arc(degree,radius)
	end

	# Store image in .pbm file
	def store()
		# Get filename of input program
		filename = ARGV[0]
		# Remove extension
		filename = File.basename(filename,".rtn")
		# Add extension
		filename << ".pbm"

		# Create new file
		newFile = File.open(filename, "w")
	
		# Add magid number and dimensions of matrix
		newFile.puts("P1")
		newFile.print(@width)
		newFile.print(' ')
		newFile.puts(@height)

		# Store matrix in file
		@image.each do |row|
			row.each do |pixel|
				newFile.print pixel, ' '
			end
			newFile.puts
		end

		# Close stream
		newFile.close
	end

	# Auxiliary function to convert x coordinate from
	# cartesian system to matrix column
	def convert_x_to_column(x)
		return (((@width-1)/2) + x).to_i
	end

	# Auxiliary function to convert y coordinate from
	# cartesian system to matrix row
	def convert_y_to_row(y)
		return (((@width-1)/2) - y).to_i
	end
end