#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative "retina_lexer.rb"
require_relative "retina_ast.rb"

class SyntacticError < RuntimeError

    def initialize(tok)
        @token = tok
    end

    def to_s
        if @token.eql? "$" then
            "Unexpected EOF"
        else
            "Line #{@token.line}, column #{@token.column}: unexpected token #{@token.symbol}: #{@token.value}"   
        end
    end
end

class Parser < Racc::Parser

module_eval(<<'...end retina_parser.y/module_eval...', 'retina_parser.y', 216)

def initialize(lexer)
    @lexer = lexer
end

def on_error(id, token, stack)
    raise SyntacticError::new(token)
end

def next_token
    if @lexer.has_next_token then
        token = @lexer.next_token;
        return [token.symbol,token]
    else
        return nil
    end
end

def parse
    do_parse
end
...end retina_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    31,    42,    72,    40,     4,   108,    32,    72,    31,    57,
    58,    59,     5,     7,    32,    14,    15,     4,    18,    31,
    29,    27,    28,    19,   109,    32,    16,    17,    31,   116,
    10,    71,    11,    13,    32,    33,    43,    46,    31,    37,
    38,    10,    10,    33,    32,    62,    31,    37,    38,    63,
    10,    64,    32,    65,    33,    66,    31,    67,    37,    38,
    10,    10,    32,    33,    76,    31,    77,    37,    38,    78,
    10,    32,    10,    33,    46,    81,    31,    37,    38,    10,
    10,    33,    32,    71,    31,    37,    38,    86,    10,   111,
    32,    33,    42,    31,   113,    37,    38,   114,    10,    32,
    33,   115,    31,   121,    37,    38,   121,    10,    32,   123,
   126,    33,   140,   149,    31,    37,    38,   150,    10,    33,
    32,    46,    10,    37,    38,    31,    10,   157,    33,   158,
   159,    32,    37,    38,    31,    10,   160,    33,   161,   167,
    32,    37,    38,   169,    10,    31,    57,    58,    59,    33,
   171,    32,   179,    37,    38,    31,    10,   184,   187,   nil,
    33,    32,   nil,   nil,    37,    38,    31,    10,   nil,    33,
   nil,   nil,    32,    37,    38,    31,    10,   nil,   nil,   nil,
    33,    32,   nil,    31,    37,    38,   nil,    10,   nil,    32,
    33,   nil,    31,   nil,    37,    38,   100,    10,    32,   nil,
   nil,    33,   nil,   nil,   nil,    37,    38,   100,    10,   nil,
    33,   104,   nil,   nil,    37,    38,   nil,    10,    33,   nil,
    31,   nil,    37,    38,   nil,    10,    32,    33,   nil,   nil,
   nil,    37,    38,   nil,    10,   127,   128,   nil,   131,   nil,
   nil,   nil,   nil,   132,   nil,   nil,   129,   130,    31,   nil,
   nil,   nil,   139,   nil,    32,    33,   nil,   nil,   nil,    37,
    38,   nil,    10,   142,    15,   nil,    18,   nil,    29,    27,
    28,    19,   nil,   nil,    16,    17,    31,   nil,   nil,   nil,
   nil,   nil,    32,    33,   nil,   nil,   nil,    37,    38,   nil,
    10,   144,    15,   nil,    18,   nil,    29,    27,    28,    19,
   nil,   nil,    16,    17,    31,   nil,   nil,   nil,   nil,   nil,
    32,    33,   nil,   nil,   nil,    37,    38,    31,    10,   145,
    15,   nil,    18,    32,    29,    27,    28,    19,   nil,   146,
    16,    17,   nil,   nil,   nil,    31,   nil,   nil,   nil,    33,
   nil,    32,   nil,    37,    38,   nil,    10,   nil,    31,   nil,
   148,   128,    33,   131,    32,   nil,    37,    38,   132,    10,
    31,   129,   130,   nil,   nil,   nil,    32,   139,   nil,   nil,
    33,   nil,    31,   nil,    37,    38,   nil,    10,    32,   nil,
    31,   nil,   nil,    33,   nil,   nil,    32,    37,    38,   nil,
    10,   nil,   nil,   nil,   nil,    33,   nil,   nil,   nil,    37,
    38,   nil,    10,   nil,   nil,   nil,   nil,    33,   nil,   nil,
    31,    37,    38,   nil,    10,    33,    32,   nil,    31,    37,
    38,   nil,    10,   nil,    32,   164,    15,   nil,    18,   nil,
    29,    27,    28,    19,   nil,   nil,    16,    17,    57,    58,
    59,    60,    61,    55,    56,    33,   nil,   nil,    31,    37,
    38,   nil,    10,    33,    32,   nil,   nil,    37,    38,   nil,
    10,   nil,   nil,   174,   128,   nil,   131,   nil,   nil,   nil,
   nil,   132,   nil,   nil,   129,   130,    31,   nil,   nil,   nil,
   139,   nil,    32,    33,   nil,   nil,   nil,    37,    38,   nil,
    10,   177,    15,   nil,    18,   nil,    29,    27,    28,    19,
   nil,   nil,    16,    17,    31,   nil,   nil,   nil,   nil,   nil,
    32,    33,   nil,   nil,   nil,    37,    38,    31,    10,   178,
   128,   nil,   131,    32,   nil,   nil,    31,   132,   nil,   nil,
   129,   130,    32,   nil,   nil,   nil,   139,   nil,   nil,    33,
   nil,   nil,   nil,    37,    38,   nil,    10,   nil,   nil,   nil,
   nil,   nil,    33,   nil,    31,   nil,    37,    38,   nil,    10,
    32,    33,   nil,   nil,   nil,    37,    38,   nil,    10,   189,
   128,   nil,   131,   nil,   nil,   nil,   nil,   132,   nil,   nil,
   129,   130,    31,   nil,   nil,   nil,   139,   nil,    32,    33,
   nil,   nil,   nil,    37,    38,   nil,    10,   191,   128,   nil,
   131,   nil,   nil,   nil,   nil,   132,   nil,   nil,   129,   130,
    31,   nil,   nil,   nil,   139,   nil,    32,    33,   nil,   nil,
   nil,    37,    38,   nil,    10,   192,   128,   nil,   131,   nil,
   nil,   nil,   nil,   132,   nil,   193,   129,   130,    31,   nil,
   nil,   nil,   139,   nil,    32,    33,   nil,   nil,   nil,    37,
    38,   nil,    10,   195,    15,   nil,    18,   nil,    29,    27,
    28,    19,   nil,   nil,    16,    17,    31,   nil,   nil,   nil,
   nil,   nil,    32,    33,   nil,   nil,   nil,    37,    38,    31,
    10,   196,   128,   nil,   131,    32,   nil,   nil,   nil,   132,
   nil,   nil,   129,   130,   nil,   nil,   nil,    31,   139,   nil,
   nil,    33,   nil,    32,   nil,    37,    38,   nil,    10,   nil,
   nil,   nil,   202,   128,    33,   131,   nil,   nil,    37,    38,
   132,    10,   nil,   129,   130,    31,   nil,   nil,   nil,   139,
   nil,    32,    33,   nil,   nil,   nil,    37,    38,    31,    10,
   203,    15,   nil,    18,    32,    29,    27,    28,    19,   nil,
   nil,    16,    17,   nil,   nil,   nil,    31,   nil,   nil,   nil,
    33,   nil,    32,   nil,    37,    38,   nil,    10,   nil,   nil,
   nil,   207,   128,    33,   131,   nil,   nil,    37,    38,   132,
    10,   nil,   129,   130,    31,   nil,   nil,   nil,   139,   nil,
    32,    33,   nil,   nil,   nil,    37,    38,   nil,    10,   209,
   128,   nil,   131,   nil,   nil,   nil,   nil,   132,   nil,   nil,
   129,   130,   nil,   nil,   nil,   nil,   139,   nil,   nil,    33,
   nil,   nil,   nil,    37,    38,   nil,    10,    57,    58,    59,
    60,    61,    55,    56,    53,    54,    57,    58,    59,    60,
    61,    55,    56,    53,    54,    57,    58,    59,    60,    61,
    55,    56,    53,    54,    57,    58,    59,    60,    61,    55,
    56,    53,    54,   122,    57,    58,    59,    60,    61,    55,
    56,    53,   122,    57,    58,    59,    60,    61,   -83,   -83,
   nil,   124,    57,    58,    59,    60,    61,   -83,   -83,    52,
    57,    58,    59,    60,    61,    55,    56,    53,    54,    57,
    58,    59,    60,    61,    55,    56,    53,    54,    57,    58,
    59,    60,    61,    55,    56,    53,    54,   nil,   nil,   nil,
   nil,   nil,   nil,   176,   nil,   156,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   107,   nil,   nil,   175,    57,    58,    59,
    60,    61,    55,    56,    53,    54,   nil,   nil,   nil,   nil,
   nil,   nil,   201,    57,    58,    59,    60,    61,    55,    56,
    53,    54,   nil,   nil,   nil,   200,    57,    58,    59,    60,
    61,    55,    56,    53,    54,   nil,   nil,   nil,   nil,   nil,
   143,    57,    58,    59,    60,    61,    55,    56,    53,    54,
   nil,   nil,   nil,   190,    57,    58,    59,    60,    61,    55,
    56,    53,    54,    88,    57,    58,    59,    60,    61,    55,
    56,    53,    54,   nil,   nil,   nil,   173,   nil,   nil,   nil,
   nil,    87,    57,    58,    59,    60,    61,    55,    56,    53,
    54,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   172,
    57,    58,    59,    60,    61,    55,    56,    53,    54,   nil,
   nil,   nil,   nil,   nil,   nil,    85,    57,    58,    59,    60,
    61,    55,    56,    53,    54,   nil,   nil,   nil,   nil,   nil,
   nil,   170,    57,    58,    59,    60,    61,    55,    56,    53,
    54,   nil,   nil,   nil,   nil,   nil,   nil,   194,    57,    58,
    59,    60,    61,    55,    56,    53,    54,   nil,   nil,   nil,
   nil,   nil,   nil,   206,    57,    58,    59,    60,    61,    55,
    56,    53,    54,    57,    58,    59,    60,    61,    55,    56,
    53,    54 ]

racc_action_check = [
    12,    13,    84,    13,     0,    76,    12,    30,    16,    96,
    96,    96,     1,     2,    16,    12,    12,     3,    12,    18,
    12,    12,    12,    12,    76,    18,    12,    12,    19,    84,
     4,    30,     5,     9,    19,    12,    14,    15,    31,    12,
    12,    17,    12,    16,    31,    21,    32,    16,    16,    22,
    16,    23,    32,    24,    18,    25,    33,    26,    18,    18,
    29,    18,    33,    19,    39,    53,    40,    19,    19,    41,
    19,    53,    42,    31,    44,    45,    54,    31,    31,    46,
    31,    32,    54,    48,    55,    32,    32,    49,    32,    77,
    55,    33,    78,    56,    81,    33,    33,    82,    33,    56,
    53,    83,    57,    98,    53,    53,   101,    53,    57,   103,
   109,    54,   111,   126,    58,    54,    54,   127,    54,    55,
    58,   128,   130,    55,    55,    59,    55,   134,    56,   135,
   136,    59,    56,    56,    60,    56,   137,    57,   138,   148,
    60,    57,    57,   151,    57,    61,    97,    97,    97,    58,
   153,    61,   169,    58,    58,    68,    58,   174,   178,   nil,
    59,    68,   nil,   nil,    59,    59,    69,    59,   nil,    60,
   nil,   nil,    69,    60,    60,    71,    60,   nil,   nil,   nil,
    61,    71,   nil,    72,    61,    61,   nil,    61,   nil,    72,
    68,   nil,    86,   nil,    68,    68,    68,    68,    86,   nil,
   nil,    69,   nil,   nil,   nil,    69,    69,    69,    69,   nil,
    71,    71,   nil,   nil,    71,    71,   nil,    71,    72,   nil,
   110,   nil,    72,    72,   nil,    72,   110,    86,   nil,   nil,
   nil,    86,    86,   nil,    86,   110,   110,   nil,   110,   nil,
   nil,   nil,   nil,   110,   nil,   nil,   110,   110,   117,   nil,
   nil,   nil,   110,   nil,   117,   110,   nil,   nil,   nil,   110,
   110,   nil,   110,   117,   117,   nil,   117,   nil,   117,   117,
   117,   117,   nil,   nil,   117,   117,   119,   nil,   nil,   nil,
   nil,   nil,   119,   117,   nil,   nil,   nil,   117,   117,   nil,
   117,   119,   119,   nil,   119,   nil,   119,   119,   119,   119,
   nil,   nil,   119,   119,   120,   nil,   nil,   nil,   nil,   nil,
   120,   119,   nil,   nil,   nil,   119,   119,   124,   119,   120,
   120,   nil,   120,   124,   120,   120,   120,   120,   nil,   120,
   120,   120,   nil,   nil,   nil,   125,   nil,   nil,   nil,   120,
   nil,   125,   nil,   120,   120,   nil,   120,   nil,   129,   nil,
   125,   125,   124,   125,   129,   nil,   124,   124,   125,   124,
   131,   125,   125,   nil,   nil,   nil,   131,   125,   nil,   nil,
   125,   nil,   132,   nil,   125,   125,   nil,   125,   132,   nil,
   139,   nil,   nil,   129,   nil,   nil,   139,   129,   129,   nil,
   129,   nil,   nil,   nil,   nil,   131,   nil,   nil,   nil,   131,
   131,   nil,   131,   nil,   nil,   nil,   nil,   132,   nil,   nil,
   141,   132,   132,   nil,   132,   139,   141,   nil,   143,   139,
   139,   nil,   139,   nil,   143,   141,   141,   nil,   141,   nil,
   141,   141,   141,   141,   nil,   nil,   141,   141,    89,    89,
    89,    89,    89,    89,    89,   141,   nil,   nil,   163,   141,
   141,   nil,   141,   143,   163,   nil,   nil,   143,   143,   nil,
   143,   nil,   nil,   163,   163,   nil,   163,   nil,   nil,   nil,
   nil,   163,   nil,   nil,   163,   163,   166,   nil,   nil,   nil,
   163,   nil,   166,   163,   nil,   nil,   nil,   163,   163,   nil,
   163,   166,   166,   nil,   166,   nil,   166,   166,   166,   166,
   nil,   nil,   166,   166,   168,   nil,   nil,   nil,   nil,   nil,
   168,   166,   nil,   nil,   nil,   166,   166,   171,   166,   168,
   168,   nil,   168,   171,   nil,   nil,   175,   168,   nil,   nil,
   168,   168,   175,   nil,   nil,   nil,   168,   nil,   nil,   168,
   nil,   nil,   nil,   168,   168,   nil,   168,   nil,   nil,   nil,
   nil,   nil,   171,   nil,   180,   nil,   171,   171,   nil,   171,
   180,   175,   nil,   nil,   nil,   175,   175,   nil,   175,   180,
   180,   nil,   180,   nil,   nil,   nil,   nil,   180,   nil,   nil,
   180,   180,   182,   nil,   nil,   nil,   180,   nil,   182,   180,
   nil,   nil,   nil,   180,   180,   nil,   180,   182,   182,   nil,
   182,   nil,   nil,   nil,   nil,   182,   nil,   nil,   182,   182,
   183,   nil,   nil,   nil,   182,   nil,   183,   182,   nil,   nil,
   nil,   182,   182,   nil,   182,   183,   183,   nil,   183,   nil,
   nil,   nil,   nil,   183,   nil,   183,   183,   183,   186,   nil,
   nil,   nil,   183,   nil,   186,   183,   nil,   nil,   nil,   183,
   183,   nil,   183,   186,   186,   nil,   186,   nil,   186,   186,
   186,   186,   nil,   nil,   186,   186,   188,   nil,   nil,   nil,
   nil,   nil,   188,   186,   nil,   nil,   nil,   186,   186,   190,
   186,   188,   188,   nil,   188,   190,   nil,   nil,   nil,   188,
   nil,   nil,   188,   188,   nil,   nil,   nil,   198,   188,   nil,
   nil,   188,   nil,   198,   nil,   188,   188,   nil,   188,   nil,
   nil,   nil,   198,   198,   190,   198,   nil,   nil,   190,   190,
   198,   190,   nil,   198,   198,   199,   nil,   nil,   nil,   198,
   nil,   199,   198,   nil,   nil,   nil,   198,   198,   200,   198,
   199,   199,   nil,   199,   200,   199,   199,   199,   199,   nil,
   nil,   199,   199,   nil,   nil,   nil,   205,   nil,   nil,   nil,
   199,   nil,   205,   nil,   199,   199,   nil,   199,   nil,   nil,
   nil,   205,   205,   200,   205,   nil,   nil,   200,   200,   205,
   200,   nil,   205,   205,   208,   nil,   nil,   nil,   205,   nil,
   208,   205,   nil,   nil,   nil,   205,   205,   nil,   205,   208,
   208,   nil,   208,   nil,   nil,   nil,   nil,   208,   nil,   nil,
   208,   208,   nil,   nil,   nil,   nil,   208,   nil,   nil,   208,
   nil,   nil,   nil,   208,   208,   nil,   208,    99,    99,    99,
    99,    99,    99,    99,    99,    99,   102,   102,   102,   102,
   102,   102,   102,   102,   102,   105,   105,   105,   105,   105,
   105,   105,   105,   105,    20,    20,    20,    20,    20,    20,
    20,    20,    20,    99,    90,    90,    90,    90,    90,    90,
    90,    90,   102,    91,    91,    91,    91,    91,    91,    91,
   nil,   105,    92,    92,    92,    92,    92,    92,    92,    20,
   133,   133,   133,   133,   133,   133,   133,   133,   133,    75,
    75,    75,    75,    75,    75,    75,    75,    75,   165,   165,
   165,   165,   165,   165,   165,   165,   165,   nil,   nil,   nil,
   nil,   nil,   nil,   165,   nil,   133,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    75,   nil,   nil,   165,   197,   197,   197,
   197,   197,   197,   197,   197,   197,   nil,   nil,   nil,   nil,
   nil,   nil,   197,   118,   118,   118,   118,   118,   118,   118,
   118,   118,   nil,   nil,   nil,   197,   181,   181,   181,   181,
   181,   181,   181,   181,   181,   nil,   nil,   nil,   nil,   nil,
   118,    51,    51,    51,    51,    51,    51,    51,    51,    51,
   nil,   nil,   nil,   181,   155,   155,   155,   155,   155,   155,
   155,   155,   155,    51,    50,    50,    50,    50,    50,    50,
    50,    50,    50,   nil,   nil,   nil,   155,   nil,   nil,   nil,
   nil,    50,   154,   154,   154,   154,   154,   154,   154,   154,
   154,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   154,
    47,    47,    47,    47,    47,    47,    47,    47,    47,   nil,
   nil,   nil,   nil,   nil,   nil,    47,   152,   152,   152,   152,
   152,   152,   152,   152,   152,   nil,   nil,   nil,   nil,   nil,
   nil,   152,   185,   185,   185,   185,   185,   185,   185,   185,
   185,   nil,   nil,   nil,   nil,   nil,   nil,   185,   204,   204,
   204,   204,   204,   204,   204,   204,   204,   nil,   nil,   nil,
   nil,   nil,   nil,   204,   106,   106,   106,   106,   106,   106,
   106,   106,   106,   162,   162,   162,   162,   162,   162,   162,
   162,   162 ]

racc_action_pointer = [
   -30,    12,    -3,   -17,   -15,    32,   nil,   nil,   nil,    -5,
   nil,   nil,    -3,   -36,    -4,     0,     5,    -4,    16,    25,
   849,     5,     9,    11,    13,    15,    17,   nil,   nil,    15,
    -7,    35,    43,    53,   nil,   nil,   nil,   nil,   nil,    25,
    49,    28,    27,   nil,    37,    35,    34,  1035,    45,    56,
   999,   976,   nil,    62,    73,    81,    90,    99,   111,   122,
   131,   142,   nil,   nil,   nil,   nil,   nil,   nil,   152,   163,
   nil,   172,   180,   nil,   nil,   894,   -12,    53,    55,   nil,
   nil,    74,    57,    61,   -12,   nil,   189,   nil,   nil,   433,
   859,   868,   877,   nil,   nil,   nil,     4,   141,    62,   822,
   nil,    65,   831,    70,   nil,   840,  1099,   nil,   nil,    73,
   217,    75,   nil,   nil,   nil,   nil,   nil,   245,   948,   273,
   301,   nil,   nil,   nil,   314,   332,    96,    77,    84,   345,
    77,   357,   369,   885,    87,    89,    90,    96,    98,   377,
   nil,   407,   nil,   415,   nil,   nil,   nil,   nil,    99,   nil,
   nil,   103,  1051,   119,  1017,   989,   nil,   nil,   nil,   nil,
   nil,   nil,  1108,   445,   nil,   903,   473,   nil,   501,   132,
   nil,   514,   nil,   nil,   117,   523,   nil,   nil,   118,   nil,
   551,   961,   579,   607,   nil,  1067,   635,   nil,   663,   nil,
   676,   nil,   nil,   nil,   nil,   nil,   nil,   932,   694,   722,
   735,   nil,   nil,   nil,  1083,   753,   nil,   nil,   781,   nil ]

racc_action_default = [
    -5,   -83,    -2,    -5,   -83,   -83,    -1,   -33,    -4,   -83,
   -82,   210,   -83,   -83,   -83,   -11,   -83,   -83,   -83,   -83,
   -83,   -83,   -83,   -83,   -83,   -83,   -83,   -47,   -47,   -83,
   -76,   -83,   -83,   -83,   -74,   -75,   -77,   -80,   -81,   -83,
   -83,   -54,   -83,    -3,   -11,   -83,   -83,   -83,   -76,   -83,
   -83,   -83,   -26,   -83,   -83,   -83,   -83,   -83,   -83,   -83,
   -83,   -83,   -27,   -28,   -29,   -30,   -31,   -32,   -83,   -83,
   -48,   -83,   -83,   -64,   -72,   -83,   -83,   -40,   -83,   -78,
   -10,   -83,   -83,   -83,   -58,   -33,   -83,   -33,   -33,   -62,
   -63,   -65,   -66,   -67,   -68,   -69,   -70,   -71,   -41,   -42,
   -79,   -43,   -44,   -83,   -50,   -56,   -59,   -73,   -40,   -83,
   -83,   -83,   -53,   -33,   -51,   -52,   -57,   -83,   -83,   -83,
   -83,   -45,   -46,   -49,   -83,   -83,   -83,   -83,   -11,   -83,
   -83,   -83,   -83,   -83,   -83,   -83,   -83,   -83,   -83,   -60,
   -40,   -83,   -14,   -83,   -17,   -22,   -33,   -55,   -83,   -40,
    -8,   -83,   -83,   -83,   -83,   -83,   -34,   -35,   -36,   -37,
   -38,   -39,   -61,   -83,   -12,   -83,   -83,    -6,   -83,   -83,
   -40,   -83,   -40,   -40,   -83,   -83,   -33,   -23,   -83,   -40,
   -83,   -83,   -83,   -83,    -9,   -83,   -83,    -7,   -83,   -18,
   -83,   -21,   -24,   -40,   -33,   -16,   -13,   -83,   -83,   -83,
   -83,   -40,   -25,   -15,   -83,   -83,   -40,   -20,   -83,   -19 ]

racc_goto_table = [
     9,    12,    39,     2,     1,    45,     8,     6,    30,   103,
    68,    69,    20,    49,    98,   101,    47,    82,    50,    51,
   nil,   nil,   nil,   nil,   nil,    70,   nil,   nil,   nil,   nil,
   nil,    73,    74,    75,    80,   nil,   nil,   nil,    79,    21,
   nil,   nil,    84,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    89,    90,    91,    92,    93,    94,    95,
    96,    97,   147,   nil,   nil,   nil,   nil,   112,    99,   102,
   nil,   105,   106,    83,   nil,   nil,   nil,   nil,   nil,   117,
   nil,   119,   120,   nil,   nil,   nil,   118,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    30,   141,   nil,   nil,
   nil,   nil,   nil,    30,   nil,    30,    30,    20,   151,    20,
    20,    30,   nil,   nil,   105,   nil,   153,   nil,   nil,   152,
   nil,   154,   155,   nil,   110,   nil,   nil,    30,   nil,   162,
   166,    20,   nil,   165,    21,   nil,    21,    21,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    30,
   nil,   nil,    30,   nil,    30,   125,    20,   nil,    21,   nil,
   186,   181,   nil,   nil,   nil,   185,    30,   nil,    30,    30,
   nil,   nil,    30,   nil,    30,   nil,    20,   nil,   199,   nil,
   197,   nil,   nil,    21,    30,    30,   nil,   163,   nil,    20,
   204,    30,   nil,   nil,    30,   nil,   168,   nil,   nil,   nil,
   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    21,   180,   nil,   182,
   183,   nil,   nil,   nil,   nil,   nil,   188,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   198,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   205,   nil,
   nil,   nil,   nil,   208 ]

racc_goto_check = [
     6,     4,     7,     2,     1,     9,     2,     3,     6,    25,
    22,    22,    14,     6,    23,    23,    14,    26,    14,    14,
   nil,   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,
   nil,    14,    14,    14,     9,   nil,   nil,   nil,     6,    18,
   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    14,    14,    14,    14,    14,    14,    14,
    14,    14,    25,   nil,   nil,   nil,   nil,     7,    14,    14,
   nil,    14,    14,    18,   nil,   nil,   nil,   nil,   nil,     4,
   nil,     4,     4,   nil,   nil,   nil,    14,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     6,     4,   nil,   nil,
   nil,   nil,   nil,     6,   nil,     6,     6,    14,     9,    14,
    14,     6,   nil,   nil,    14,   nil,     6,   nil,   nil,    14,
   nil,    14,    14,   nil,     8,   nil,   nil,     6,   nil,    14,
     4,    14,   nil,    14,    18,   nil,    18,    18,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,
   nil,   nil,     6,   nil,     6,     8,    14,   nil,    18,   nil,
     4,    14,   nil,   nil,   nil,    14,     6,   nil,     6,     6,
   nil,   nil,     6,   nil,     6,   nil,    14,   nil,     4,   nil,
    14,   nil,   nil,    18,     6,     6,   nil,     8,   nil,    14,
    14,     6,   nil,   nil,     6,   nil,     8,   nil,   nil,   nil,
   nil,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    18,     8,   nil,     8,
     8,   nil,   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     8,   nil,
   nil,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,     4,     3,     5,    -6,   nil,    -4,   -11,    57,   -10,
   nil,   nil,   nil,   nil,     0,   nil,   nil,   nil,    27,   nil,
   nil,   nil,   -17,   -54,   nil,   -62,   -29,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     3,    48,   nil,   nil,   nil,
    44,    24,   137,    23,   133,   136,    22,   135,   134,    25,
    26,   138,   nil,   nil,    36,   nil,   nil,    41,    34,    35 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 47, :_reduce_none,
  1, 47, :_reduce_none,
  4, 49, :_reduce_none,
  2, 48, :_reduce_none,
  0, 48, :_reduce_none,
  9, 51, :_reduce_none,
  11, 51, :_reduce_none,
  8, 51, :_reduce_none,
  10, 51, :_reduce_none,
  2, 55, :_reduce_none,
  0, 55, :_reduce_none,
  6, 57, :_reduce_none,
  6, 58, :_reduce_none,
  5, 59, :_reduce_none,
  11, 59, :_reduce_none,
  9, 59, :_reduce_none,
  5, 59, :_reduce_none,
  5, 61, :_reduce_none,
  11, 61, :_reduce_none,
  9, 61, :_reduce_none,
  5, 61, :_reduce_none,
  5, 62, :_reduce_none,
  7, 62, :_reduce_none,
  5, 63, :_reduce_none,
  7, 63, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  0, 50, :_reduce_none,
  3, 54, :_reduce_none,
  3, 54, :_reduce_none,
  3, 54, :_reduce_none,
  3, 54, :_reduce_none,
  3, 54, :_reduce_none,
  3, 54, :_reduce_none,
  0, 54, :_reduce_none,
  3, 66, :_reduce_none,
  3, 66, :_reduce_none,
  3, 66, :_reduce_none,
  3, 66, :_reduce_none,
  3, 68, :_reduce_none,
  3, 68, :_reduce_none,
  0, 68, :_reduce_none,
  2, 65, :_reduce_none,
  4, 70, :_reduce_none,
  3, 70, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 53, :_reduce_none,
  1, 53, :_reduce_none,
  3, 71, :_reduce_none,
  1, 71, :_reduce_none,
  2, 72, :_reduce_none,
  1, 72, :_reduce_none,
  3, 64, :_reduce_none,
  1, 67, :_reduce_none,
  2, 67, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  2, 60, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  3, 60, :_reduce_none,
  2, 60, :_reduce_none,
  3, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  1, 60, :_reduce_none,
  2, 73, :_reduce_none,
  1, 69, :_reduce_none,
  1, 74, :_reduce_none,
  1, 75, :_reduce_none,
  1, 52, :_reduce_none ]

racc_reduce_n = 83

racc_shift_n = 210

racc_token_table = {
  false => 0,
  :error => 1,
  :PRNTS => 2,
  :NOT => 3,
  :UMINUS => 4,
  :MULT => 5,
  :DIV => 6,
  :MOD => 7,
  :PLUS => 8,
  :MINUS => 9,
  :EQUALITYOP => 10,
  :ORDEROP => 11,
  :AND => 12,
  :OR => 13,
  :ASSIGNOP => 14,
  :SEMICOLON => 15,
  :PROGRAM => 16,
  :BEGINBLK => 17,
  :ENDBLK => 18,
  :WITH => 19,
  :DO => 20,
  :REPEAT => 21,
  :TIMES => 22,
  :READ => 23,
  :WRITE => 24,
  :WRITELN => 25,
  :IF => 26,
  :THEN => 27,
  :ELSE => 28,
  :WHILE => 29,
  :FOR => 30,
  :FROM => 31,
  :TO => 32,
  :BY => 33,
  :FUNC => 34,
  :RETURN => 35,
  :RETURNTYPE => 36,
  :TYPE => 37,
  :LPARENTH => 38,
  :RPARENTH => 39,
  :SEP => 40,
  :COLON => 41,
  :BOOLEAN => 42,
  :NUMBER => 43,
  :STRING => 44,
  :IDENTIFIER => 45 }

racc_nt_base = 46

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "PRNTS",
  "NOT",
  "UMINUS",
  "MULT",
  "DIV",
  "MOD",
  "PLUS",
  "MINUS",
  "EQUALITYOP",
  "ORDEROP",
  "AND",
  "OR",
  "ASSIGNOP",
  "SEMICOLON",
  "PROGRAM",
  "BEGINBLK",
  "ENDBLK",
  "WITH",
  "DO",
  "REPEAT",
  "TIMES",
  "READ",
  "WRITE",
  "WRITELN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "FROM",
  "TO",
  "BY",
  "FUNC",
  "RETURN",
  "RETURNTYPE",
  "TYPE",
  "LPARENTH",
  "RPARENTH",
  "SEP",
  "COLON",
  "BOOLEAN",
  "NUMBER",
  "STRING",
  "IDENTIFIER",
  "$start",
  "retina",
  "defblk",
  "programblk",
  "instr",
  "funcdef",
  "ident",
  "paramlist",
  "funcinstr",
  "declblk",
  "decl",
  "withblk",
  "funcwithblk",
  "iter",
  "expr",
  "funciter",
  "cond",
  "funccond",
  "assign",
  "readblk",
  "writeblk",
  "returnblk",
  "writelist",
  "str",
  "callfunc",
  "arglist",
  "identlist",
  "param",
  "b",
  "n" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
